-- tests/lua/parser/schema_spec.lua
-- Schema Module Tests - TDD Phase (RED)
-- Tests for AST schema definitions

describe("AST Schema Module", function()
  local schema

  before_each(function()
    package.loaded["tcl-lsp.parser.schema"] = nil
    schema = require "tcl-lsp.parser.schema"
  end)

  describe("Type Validators", function()
    it("should have string type validator", function()
      assert.is_table(schema.types)
      assert.is_function(schema.types.string)
      assert.is_true(schema.types.string "hello")
      assert.is_false(schema.types.string(123))
      assert.is_false(schema.types.string({}))
    end)

    it("should have number type validator", function()
      assert.is_function(schema.types.number)
      assert.is_true(schema.types.number(42))
      assert.is_true(schema.types.number(3.14))
      assert.is_false(schema.types.number "42")
      assert.is_false(schema.types.number({}))
    end)

    it("should have boolean type validator", function()
      assert.is_function(schema.types.boolean)
      assert.is_true(schema.types.boolean(true))
      assert.is_true(schema.types.boolean(false))
      assert.is_false(schema.types.boolean(1))
      assert.is_false(schema.types.boolean "true")
    end)

    it("should have array type validator", function()
      assert.is_function(schema.types.array)
      assert.is_true(schema.types.array { 1, 2, 3 })
      assert.is_true(schema.types.array {})
      assert.is_false(schema.types.array { a = 1 })
      assert.is_false(schema.types.array "array")
    end)

    it("should have object type validator", function()
      assert.is_function(schema.types.object)
      assert.is_true(schema.types.object { a = 1 })
      assert.is_true(schema.types.object {})
      assert.is_false(schema.types.object { 1, 2, 3 })
      assert.is_false(schema.types.object "object")
    end)

    it("should have any type validator", function()
      assert.is_function(schema.types.any)
      assert.is_true(schema.types.any "hello")
      assert.is_true(schema.types.any(123))
      assert.is_true(schema.types.any {})
      assert.is_true(schema.types.any(nil))
    end)

    it("should have tcl_boolean type validator", function()
      assert.is_function(schema.types.tcl_boolean)
      assert.is_true(schema.types.tcl_boolean(true))
      assert.is_true(schema.types.tcl_boolean(false))
      assert.is_true(schema.types.tcl_boolean(0))
      assert.is_true(schema.types.tcl_boolean(1))
      assert.is_false(schema.types.tcl_boolean(2))
      assert.is_false(schema.types.tcl_boolean "true")
    end)

    it("should have tcl_array type validator", function()
      assert.is_function(schema.types.tcl_array)
      assert.is_true(schema.types.tcl_array { 1, 2, 3 })
      assert.is_true(schema.types.tcl_array {})
      assert.is_true(schema.types.tcl_array "") -- Empty string is valid
      assert.is_false(schema.types.tcl_array { a = 1 })
      assert.is_false(schema.types.tcl_array "non-empty")
    end)
  end)

  describe("Position Schema", function()
    it("should define position schema with line and column", function()
      assert.is_table(schema.position)
      assert.is_table(schema.position.line)
      assert.is_table(schema.position.column)

      assert.equals("number", schema.position.line.type)
      assert.is_true(schema.position.line.required)

      assert.equals("number", schema.position.column.type)
      assert.is_true(schema.position.column.required)
    end)
  end)

  describe("Range Schema", function()
    it("should define range schema with start and end_pos", function()
      assert.is_table(schema.range)
      assert.is_table(schema.range.start)
      assert.is_table(schema.range.end_pos)

      -- start position
      assert.is_true(schema.range.start.required)
      assert.equals("object", schema.range.start.type)
      assert.is_table(schema.range.start.fields)

      -- end_pos position
      assert.is_true(schema.range.end_pos.required)
      assert.equals("object", schema.range.end_pos.type)
      assert.is_table(schema.range.end_pos.fields)
    end)
  end)

  describe("Body Schema", function()
    it("should define body schema with children array", function()
      assert.is_table(schema.body)
      assert.is_table(schema.body.children)
      assert.equals("array", schema.body.children.type)
      assert.is_true(schema.body.children.required)
    end)
  end)

  describe("Parameter Schema", function()
    it("should define param schema for proc parameters", function()
      assert.is_table(schema.param)
      assert.is_table(schema.param.name)
      assert.equals("string", schema.param.name.type)
      assert.is_true(schema.param.name.required)

      -- Optional fields
      assert.is_table(schema.param.default)
      assert.is_false(schema.param.default.required)

      assert.is_table(schema.param.is_varargs)
      assert.is_false(schema.param.is_varargs.required)
    end)
  end)

  describe("Node Schemas", function()
    it("should have nodes table with all node type schemas", function()
      assert.is_table(schema.nodes)
    end)

    describe("root node", function()
      it("should define root node schema", function()
        local node = schema.nodes.root
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.children)
        assert.is_table(node.fields.filepath)
        assert.is_table(node.fields.had_error)
        assert.is_table(node.fields.errors)
      end)
    end)

    describe("proc node", function()
      it("should define proc node schema", function()
        local node = schema.nodes.proc
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.name)
        assert.is_table(node.fields.params)
        assert.is_table(node.fields.body)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("set node", function()
      it("should define set node schema", function()
        local node = schema.nodes.set
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.var_name)
        assert.is_table(node.fields.value)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("variable node", function()
      it("should define variable node schema", function()
        local node = schema.nodes.variable
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.name)
        assert.is_table(node.fields.value)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("global node", function()
      it("should define global node schema", function()
        local node = schema.nodes.global
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.vars)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("upvar node", function()
      it("should define upvar node schema", function()
        local node = schema.nodes.upvar
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.level)
        assert.is_table(node.fields.other_var)
        assert.is_table(node.fields.local_var)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("array node", function()
      it("should define array node schema", function()
        local node = schema.nodes.array
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.operation)
        assert.is_table(node.fields.array_name)
        assert.is_table(node.fields.args)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("if node", function()
      it("should define if node schema", function()
        local node = schema.nodes["if"]
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.condition)
        assert.is_table(node.fields.then_body)
        assert.is_table(node.fields.else_body)
        assert.is_table(node.fields.elseif_branches)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("while node", function()
      it("should define while node schema", function()
        local node = schema.nodes["while"]
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.condition)
        assert.is_table(node.fields.body)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("for node", function()
      it("should define for node schema", function()
        local node = schema.nodes["for"]
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.init)
        assert.is_table(node.fields.condition)
        assert.is_table(node.fields.increment)
        assert.is_table(node.fields.body)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("foreach node", function()
      it("should define foreach node schema", function()
        local node = schema.nodes.foreach
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.var_name)
        assert.is_table(node.fields.list)
        assert.is_table(node.fields.body)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("switch node", function()
      it("should define switch node schema", function()
        local node = schema.nodes.switch
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.expression)
        assert.is_table(node.fields.cases)
        assert.is_table(node.fields.option)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("namespace nodes", function()
      it("should define namespace_eval node schema", function()
        local node = schema.nodes.namespace_eval
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.name)
        assert.is_table(node.fields.body)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)

      it("should define generic namespace node schema", function()
        local node = schema.nodes.namespace
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.subcommand)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)

      it("should define namespace_import node schema", function()
        local node = schema.nodes.namespace_import
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.patterns)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)

      it("should define namespace_export node schema", function()
        local node = schema.nodes.namespace_export
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.exports)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("package nodes", function()
      it("should define package node schema", function()
        local node = schema.nodes.package
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.package_name)
        assert.is_table(node.fields.version)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)

      it("should define package_require node schema", function()
        local node = schema.nodes.package_require
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.package_name)
        assert.is_table(node.fields.version)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)

      it("should define package_provide node schema", function()
        local node = schema.nodes.package_provide
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.package_name)
        assert.is_table(node.fields.version)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("source node", function()
      it("should define source node schema", function()
        local node = schema.nodes.source
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.filepath)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("expr node", function()
      it("should define expr node schema", function()
        local node = schema.nodes.expr
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.expression)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("list node", function()
      it("should define list node schema", function()
        local node = schema.nodes.list
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.elements)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("lappend node", function()
      it("should define lappend node schema", function()
        local node = schema.nodes.lappend
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.var_name)
        assert.is_table(node.fields.value)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("puts node", function()
      it("should define puts node schema", function()
        local node = schema.nodes.puts
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.args)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)

    describe("error node", function()
      it("should define error node schema", function()
        local node = schema.nodes.error
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.message)
        assert.is_table(node.fields.range)
      end)
    end)

    describe("command_substitution node", function()
      it("should define command_substitution node schema", function()
        local node = schema.nodes.command_substitution
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.command)
      end)
    end)

    describe("command node (generic fallback)", function()
      it("should define command node schema", function()
        local node = schema.nodes.command
        assert.is_table(node)
        assert.is_table(node.fields)
        assert.is_table(node.fields.type)
        assert.is_table(node.fields.name)
        assert.is_table(node.fields.args)
        assert.is_table(node.fields.range)
        assert.is_table(node.fields.depth)
      end)
    end)
  end)

  describe("Helper Functions", function()
    it("should provide get_schema_for_type function", function()
      assert.is_function(schema.get_schema_for_type)

      local proc_schema = schema.get_schema_for_type "proc"
      assert.is_table(proc_schema)
      assert.is_table(proc_schema.fields)

      local unknown_schema = schema.get_schema_for_type "unknown_type"
      assert.is_nil(unknown_schema)
    end)

    it("should provide get_all_node_types function", function()
      assert.is_function(schema.get_all_node_types)

      local types = schema.get_all_node_types()
      assert.is_table(types)
      assert.is_true(#types >= 20) -- We have at least 20 node types

      -- Check some expected types are present
      local type_set = {}
      for _, t in ipairs(types) do
        type_set[t] = true
      end
      assert.is_true(type_set["root"])
      assert.is_true(type_set["proc"])
      assert.is_true(type_set["set"])
      assert.is_true(type_set["if"])
    end)

    it("should provide is_known_node_type function", function()
      assert.is_function(schema.is_known_node_type)

      assert.is_true(schema.is_known_node_type "proc")
      assert.is_true(schema.is_known_node_type "set")
      assert.is_true(schema.is_known_node_type "if")
      assert.is_false(schema.is_known_node_type "unknown_type")
      assert.is_false(schema.is_known_node_type "")
    end)
  end)
end)
