name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ["stable", "nightly"]

    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}

      - name: Install TCL
        run: |
          sudo apt-get update
          sudo apt-get install -y tcl tcllib

      - name: Run health check
        run: |
          nvim --headless --noplugin -u tests/minimal_init.lua -c "lua require('tcl-lsp').health()" -c "qa!"

      - name: Test plugin loading
        run: |
          nvim --headless --noplugin -u tests/minimal_init.lua -c "lua require('tcl-lsp').setup()" -c "qa!"

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: Run luacheck
        run: luacheck lua/ --globals vim

  docs:
    name: Generate docs
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Generate help docs
        run: |
          nvim --headless --noplugin -u scripts/gen_docs.lua -c "qa!"

      - name: Commit docs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add doc/
          git diff --staged --quiet || git commit -m "Auto-update documentation"
          git push
